services:
    becklyn_ddd.events.event_type_repository:
        class: Becklyn\Ddd\Events\Infrastructure\Store\Doctrine\DoctrineStoredEventTypeRepository
        public: false
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'

    Becklyn\Ddd\Events\Infrastructure\Store\Doctrine\DoctrineStoredEventTypeRepository:
        alias: becklyn_ddd.events.event_type_repository

    becklyn_ddd.events.aggregate_type_repository:
        class: Becklyn\Ddd\Events\Infrastructure\Store\Doctrine\DoctrineStoredEventAggregateTypeRepository
        public: false
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'

    Becklyn\Ddd\Events\Infrastructure\Store\Doctrine\DoctrineStoredEventAggregateTypeRepository:
        alias: becklyn_ddd.events.aggregate_type_repository

    becklyn_ddd.events.aggregate_repository:
        class: Becklyn\Ddd\Events\Infrastructure\Store\Doctrine\DoctrineStoredEventAggregateRepository
        public: false
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@becklyn_ddd.events.aggregate_type_repository'

    Becklyn\Ddd\Events\Infrastructure\Store\Doctrine\DoctrineStoredEventAggregateRepository:
        alias: becklyn_ddd.events.aggregate_repository

    becklyn_ddd.events.event_store:
        class: Becklyn\Ddd\Events\Infrastructure\Store\Doctrine\DoctrineEventStore
        public: false
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@becklyn_ddd.events.aggregate_repository'
            - '@becklyn_ddd.events.event_type_repository'
            - '@Symfony\Component\Serializer\SerializerInterface'
            - true

    Becklyn\Ddd\Events\Infrastructure\Store\Doctrine\DoctrineEventStore:
        alias: becklyn_ddd.events.event_store

    Becklyn\Ddd\Events\Domain\EventStore:
        alias: becklyn_ddd.events.event_store

    becklyn_ddd.events.event_bus:
        class: Becklyn\Ddd\Events\Infrastructure\Bus\SimpleBus\SimpleBusEventBus
        public: false
        arguments:
            - '@SimpleBus\SymfonyBridge\Bus\EventBus'

    Becklyn\Ddd\Events\Infrastructure\Bus\SimpleBus\SimpleBusEventBus:
        alias: becklyn_ddd.events.event_bus

    Becklyn\Ddd\Events\Application\EventBus:
        alias: becklyn_ddd.events.event_bus

    becklyn_ddd.events.event_registry:
        class: Becklyn\Ddd\Events\Domain\EventRegistry
        public: true
        arguments:
            - '@becklyn_ddd.events.event_store'

    Becklyn\Ddd\Events\Domain\EventRegistry:
        alias: becklyn_ddd.events.event_registry

    becklyn_ddd.events.event_manager:
        class: Becklyn\Ddd\Events\Application\EventManager
        public: false
        arguments:
            - '@becklyn_ddd.events.event_registry'
            - '@becklyn_ddd.events.event_bus'

    Becklyn\Ddd\Events\Application\EventManager:
        alias: becklyn_ddd.events.event_manager

    becklyn_ddd.identity.aggregate_id_param_converter:
        class: Becklyn\Ddd\Identity\Infrastructure\Delivery\Web\Symfony\AggregateIdParamConverter
        tags:
            - { name: 'request.param_converter', converter: 'becklyn_ddd.identity.aggregate_id' }

    becklyn_ddd.transactions.transaction_manager:
        class: Becklyn\Ddd\Transactions\Infrastructure\Application\Doctrine\DoctrineTransactionManager
        public: true
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@becklyn_ddd.events.event_manager'
            - '@becklyn_ddd.events.event_store'

    Becklyn\Ddd\Transactions\Infrastructure\Application\Doctrine\DoctrineTransactionManager:
        alias: becklyn_ddd.transactions.transaction_manager

    Becklyn\Ddd\Transactions\Application\TransactionManager:
        alias: becklyn_ddd.transactions.transaction_manager

    becklyn_ddd.commands.command_bus:
        class: Becklyn\Ddd\Commands\Infrastructure\SimpleBus\SimpleBusCommandBus
        public: false
        arguments:
            - '@SimpleBus\SymfonyBridge\Bus\CommandBus'

    Becklyn\Ddd\Commands\Infrastructure\SimpleBus\SimpleBusCommandBus:
        alias: becklyn_ddd.commands.command_bus

    Becklyn\Ddd\Commands\Application\CommandBus:
        alias: becklyn_ddd.commands.command_bus